# Generated by Django 5.2.8 on 2025-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40000)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('solution_given', 'Решение предоставлено'), ('closed', 'Закрыт')], max_length=50)),
                ('source', models.CharField(choices=[('operator', 'Оператор'), ('monitoring', 'Система мониторинга'), ('partner', 'Заказчик')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='incidents_i_id_1e7266_idx')],
            },
        ),
    ]
